# Education code mapping
EDUCATION_MAPPING = {
    "1": "not literate",
    "2": "literate: below primary",
    "3": "primary",
    "4": "upper primary/middle",
    "5": "secondary",
    "6": "higher secondary",
    "7": "diploma/certificate course (up to secondary)",
    "8": "diploma/certificate course (higher secondary)",
    "9": "diploma/certificate course (graduation & above)",
    "10": "graduate",
    "11": "post graduate and above"
}

# State code to state name mapping
STATE_MAPPING = {
    "1": "JAMMU & KASHMIR",
    "2": "HIMACHAL PRADESH",
    "3": "PUNJAB",
    "4": "CHANDIGARH",
    "5": "UTTARAKHAND",
    "6": "HARYANA",
    "7": "DELHI",
    "8": "RAJASTHAN",
    "9": "UTTAR PRADESH",
    "10": "BIHAR",
    "11": "SIKKIM",
    "12": "ARUNACHAL PRADESH",
    "13": "NAGALAND",
    "14": "MANIPUR",
    "15": "MIZORAM",
    "16": "TRIPURA",
    "17": "MEGHALAYA",
    "18": "ASSAM",
    "19": "WEST BENGAL",
    "20": "JHARKHAND",
    "21": "ODISHA",
    "22": "CHHATTISGARH",
    "23": "MADHYA PRADESH",
    "24": "GUJARAT",
    "25": "DAMAN & DIU",
    "26": "D & N HAVELI",
    "27": "MAHARASHTRA",
    "28": "ANDHRA PRADESH",
    "29": "KARNATAKA",
    "30": "GOA",
    "31": "LAKSHADWEEP",
    "32": "KERALA",
    "33": "TAMIL NADU",
    "34": "PUDUCHERRY",
    "35": "A & N ISLANDS",
    "36": "TELANGANA"
} 

# Religion mapping
RELIGION_MAPPING = {
    "1": "Hinduism",
    "2": "Islam",
    "3": "Christianity",
    "4": "Sikhism",
    "5": "Jainism",
    "6": "Buddhism",
    "7": "Zoroastrianism",
    "9": "Others"
}

# Social group mapping
SOCIAL_GROUP_MAPPING = {
    "1": "Scheduled Tribe",
    "2": "Scheduled Caste",
    "3": "Other Backward Class",
    "9": "Others"
}

# District mapping by state
DISTRICT_MAPPING = {
    "1": {  # Jammu & Kashmir
        "1": "Kupwara",
        "2": "Badgam",
        "3": "Leh",
        "4": "Kargil",
        "5": "Punch",
        "6": "Rajouri",
        "7": "Kathua",
        "8": "Baramula",
        "9": "Bandipore",
        "10": "Srinagar",
        "11": "Ganderbal",
        "12": "Pulwama",
        "13": "Shupiyan",
        "14": "Anantnag",
        "15": "Kulgam",
        "16": "Doda",
        "17": "Ramban",
        "18": "Kishtwar",
        "19": "Udhampur",
        "20": "Reasi",
        "21": "Jammu",
        "22": "Samba"
    },
    "2": {  # Himachal Pradesh
        "1": "Chamba",
        "2": "Kangra",
        "3": "Lahul & Spiti",
        "4": "Kullu",
        "5": "Mandi",
        "6": "Hamirpur",
        "7": "Una",
        "8": "Bilaspur",
        "9": "Solan",
        "10": "Sirmaur",
        "11": "Shimla",
        "12": "Kinnaur"
    },
    "3": {  # Punjab
        "1": "Gurdaspur",
        "2": "Kapurthala",
        "3": "Jalandhar",
        "4": "Hoshiarpur",
        "5": "Shahid Bhagat Singh Nagar",
        "6": "Fatehgarh Sahib",
        "7": "Ludhiana",
        "8": "Moga",
        "9": "Firozpur",
        "10": "Muktsar",
        "11": "Faridkot",
        "12": "Bathinda",
        "13": "Mansa",
        "14": "Patiala",
        "15": "Amritsar",
        "16": "Tarn Taran",
        "17": "Rupnagar",
        "18": "Sahibzada Ajit Singh Nagar",
        "19": "Sangrur",
        "20": "Barnala",
        "21": "Pathankot",
        "22": "Fazilka"
    },
    "4": {  # Chandigarh
        "1": "Chandigarh"
    },
    "5": {  # Uttarakhand
        "1": "Uttarkashi",
        "2": "Chamoli",
        "3": "Rudraprayag",
        "4": "Tehri Garhwal",
        "5": "Dehradun",
        "6": "Garhwal",
        "7": "Pithoragarh",
        "8": "Bageshwar",
        "9": "Almora",
        "10": "Champawat",
        "11": "Nainital",
        "12": "Udham Singh Nagar",
        "13": "Hardwar"
    },
    "6": {  # Haryana
        "1": "Panchkula",
        "2": "Ambala",
        "3": "Yamunanagar",
        "4": "Kurukshetra",
        "5": "Kaithal",
        "6": "Karnal",
        "7": "Panipat",
        "8": "Sonipat",
        "9": "Jind",
        "10": "Fatehabad",
        "11": "Sirsa",
        "12": "Hisar",
        "13": "Bhiwani",
        "14": "Rohtak",
        "15": "Jhajjar",
        "16": "Mahendragarh",
        "17": "Rewari",
        "18": "Gurgaon",
        "19": "Mewat",
        "20": "Faridabad",
        "21": "Palwal"
    },
    "7": {  # Delhi
        "1": "North West Delhi",
        "2": "North Delhi",
        "3": "North East Delhi",
        "4": "East Delhi",
        "5": "New Delhi",
        "6": "Central Delhi",
        "7": "West Delhi",
        "8": "South West Delhi",
        "9": "South Delhi"
    },
    "8": {  # Rajasthan
        "1": "Sri Ganganagar",
        "2": "Hanumangarh",
        "3": "Bikaner",
        "4": "Churu",
        "5": "Jhunjhunun",
        "6": "Alwar",
        "7": "Bharatpur",
        "8": "Dhaulpur",
        "9": "Karauli",
        "10": "Sawai Madhopur",
        "11": "Dausa",
        "12": "Jaipur",
        "13": "Sikar",
        "14": "Nagaur",
        "15": "Jodhpur",
        "16": "Jaisalmer",
        "17": "Barmer",
        "18": "Jalor",
        "19": "Sirohi",
        "20": "Pali",
        "21": "Ajmer",
        "22": "Tonk",
        "23": "Bundi",
        "24": "Bhilwara",
        "25": "Rajsamand",
        "26": "Dungarpur",
        "27": "Banswara",
        "28": "Chittaurgarh",
        "29": "Kota",
        "30": "Baran",
        "31": "Jhalawar",
        "32": "Udaipur",
        "33": "Pratapgarh"
    },
    "9": {  # Uttar Pradesh
        "1": "Saharanpur",
        "2": "Muzaffarnagar",
        "3": "Bijnor",
        "4": "Moradabad",
        "5": "Rampur",
        "6": "Jyotiba Phule Nagar",
        "7": "Meerut",
        "8": "Baghpat",
        "9": "Ghaziabad",
        "10": "Gautam Buddha Nagar",
        "11": "Bulandshahr",
        "12": "Aligarh",
        "13": "Mahamaya Nagar",
        "14": "Mathura",
        "15": "Agra",
        "16": "Firozabad",
        "17": "Mainpuri",
        "18": "Budaun",
        "19": "Bareilly",
        "20": "Pilibhit",
        "21": "Shahjahanpur",
        "22": "Kheri",
        "23": "Sitapur",
        "24": "Hardoi",
        "25": "Unnao",
        "26": "Lucknow",
        "27": "Rae Bareli",
        "28": "Farrukhabad",
        "29": "Kannauj",
        "30": "Etawah",
        "31": "Auraiya",
        "32": "Kanpur Dehat",
        "33": "Kanpur Nagar",
        "34": "Jalaun",
        "35": "Jhansi",
        "36": "Lalitpur",
        "37": "Hamirpur",
        "38": "Mahoba",
        "39": "Banda",
        "40": "Chitrakoot",
        "41": "Fatehpur",
        "42": "Pratapgarh",
        "43": "Kaushambi",
        "44": "Allahabad",
        "45": "Bara Banki",
        "46": "Faizabad",
        "47": "Ambedkar Nagar",
        "48": "Sultanpur",
        "49": "Bahraich",
        "50": "Shrawasti",
        "51": "Balrampur",
        "52": "Gonda",
        "53": "Siddharthnagar",
        "54": "Basti",
        "55": "Sant Kabir Nagar",
        "56": "Mahrajganj",
        "57": "Gorakhpur",
        "58": "Kushinagar",
        "59": "Deoria",
        "60": "Azamgarh",
        "61": "Mau",
        "62": "Ballia",
        "63": "Jaunpur",
        "64": "Ghazipur",
        "65": "Chandauli",
        "66": "Varanasi",
        "67": "Sant Ravidas Nagar (Bhadohi)",
        "68": "Mirzapur",
        "69": "Sonbhadra",
        "70": "Etah",
        "71": "Kanshiram Nagar"
    },
    "10": {  # Bihar
        "1": "Pashchim Champaran",
        "2": "Purba Champaran",
        "3": "Sheohar",
        "4": "Sitamarhi",
        "5": "Madhubani",
        "6": "Supaul",
        "7": "Araria",
        "8": "Kishanganj",
        "9": "Purnia",
        "10": "Katihar",
        "11": "Madhepura",
        "12": "Saharsa",
        "13": "Darbhanga",
        "14": "Muzaffarpur",
        "15": "Gopalganj",
        "16": "Siwan",
        "17": "Saran",
        "18": "Vaishali",
        "19": "Samastipur",
        "20": "Begusarai",
        "21": "Khagaria",
        "22": "Bhagalpur",
        "23": "Banka",
        "24": "Munger",
        "25": "Lakhisarai",
        "26": "Sheikhpura",
        "27": "Nalanda",
        "28": "Patna",
        "29": "Bhojpur",
        "30": "Buxar",
        "31": "Kaimur (Bhabua)",
        "32": "Rohtas",
        "33": "Aurangabad",
        "34": "Gaya",
        "35": "Nawada",
        "36": "Jamui",
        "37": "Jehanabad",
        "38": "Arwal"
    },
    "11": {  # Sikkim
        "1": "North District",
        "2": "West District",
        "3": "South District",
        "4": "East District"
    },
    "12": {  # Arunachal Pradesh
        "1": "Tawang",
        "2": "West Kameng",
        "3": "East Kameng",
        "4": "Papum Pare",
        "5": "Upper Subansiri",
        "6": "West Siang",
        "7": "East Siang",
        "8": "Upper Siang",
        "9": "Changlang",
        "10": "Tirap",
        "11": "Lower Subansiri",
        "12": "Kurung Kumey",
        "13": "Dibang Valley",
        "14": "Lower Dibang Valley",
        "15": "Lohit",
        "16": "Anjaw"
    },
    "13": {  # Nagaland
        "1": "Mon",
        "2": "Mokokchung",
        "3": "Zunheboto",
        "4": "Wokha",
        "5": "Dimapur",
        "6": "Phek",
        "7": "Tuensang",
        "8": "Longleng",
        "9": "Kiphire",
        "10": "Kohima",
        "11": "Peren"
    },
    "14": {  # Manipur
        "1": "Senapati",
        "2": "Tamenglong",
        "3": "Churachandpur",
        "4": "Bishnupur",
        "5": "Thoubal",
        "6": "Imphal West",
        "7": "Imphal East",
        "8": "Ukhrul",
        "9": "Chandel"
    },
    "15": {  # Mizoram
        "1": "Mamit",
        "2": "Kolasib",
        "3": "Aizawl",
        "4": "Champhai",
        "5": "Serchhip",
        "6": "Lunglei",
        "7": "Lawngtlai",
        "8": "Saiha"
    },
    "16": {  # Tripura
        "1": "West Tripura",
        "2": "South Tripura",
        "3": "Dhalai",
        "4": "North Tripura"
    },
    "17": {  # Meghalaya
        "1": "West Garo Hills",
        "2": "East Garo Hills",
        "3": "South Garo Hills",
        "4": "West Khasi Hills",
        "5": "Ribhoi",
        "6": "East Khasi Hills",
        "7": "Jaintia Hills"
    },
    "18": {  # Assam
        "1": "Kokrajhar",
        "2": "Dhubri",
        "3": "Goalpara",
        "4": "Barpeta",
        "5": "Morigaon",
        "6": "Nagaon",
        "7": "Sonitpur",
        "8": "Lakhimpur",
        "9": "Dhemaji",
        "10": "Tinsukia",
        "11": "Dibrugarh",
        "12": "Sivasagar",
        "13": "Jorhat",
        "14": "Golaghat",
        "15": "Karbi Anglong",
        "16": "Dima Hasao",
        "17": "Cachar",
        "18": "Karimganj",
        "19": "Hailakandi",
        "20": "Bongaigaon",
        "21": "Chirang",
        "22": "Kamrup",
        "23": "Kamrup Metropolitan",
        "24": "Nalbari",
        "25": "Baksa",
        "26": "Darrang",
        "27": "Udalguri"
    },
    "19": {  # West Bengal
        "1": "Darjiling",
        "2": "Jalpaiguri",
        "3": "Koch Bihar",
        "4": "Uttar Dinajpur",
        "5": "Dakshin Dinajpur",
        "6": "Maldah",
        "7": "Murshidabad",
        "8": "Birbhum",
        "9": "Purba Barddhaman",
        "10": "Nadia",
        "11": "North Twenty Four Parganas",
        "12": "Hugli",
        "13": "Bankura",
        "14": "Puruliya",
        "15": "Haora",
        "16": "Kolkata",
        "17": "South Twenty Four Parganas",
        "18": "Paschim Medinipur",
        "19": "Purba Medinipur",
        "20": "Alipurduar",
        "21": "Kalimpong",
        "22": "Jhargram",
        "23": "Paschim Barddhaman"
    },
    "20": {  # Jharkhand
        "1": "Garhwa",
        "2": "Chatra",
        "3": "Kodarma",
        "4": "Giridih",
        "5": "Deoghar",
        "6": "Godda",
        "7": "Sahibganj",
        "8": "Pakur",
        "9": "Dhanbad",
        "10": "Bokaro",
        "11": "Lohardaga",
        "12": "Purbi Singhbhum",
        "13": "Palamu",
        "14": "Latehar",
        "15": "Hazaribagh",
        "16": "Ramgarh",
        "17": "Dumka",
        "18": "Jamtara",
        "19": "Ranchi",
        "20": "Khunti",
        "21": "Gumla",
        "22": "Simdega",
        "23": "Pashchimi Singhbhum",
        "24": "Saraikela-Kharsawan"
    },
    "21": {  # Odisha
        "1": "Bargarh",
        "2": "Jharsuguda",
        "3": "Sambalpur",
        "4": "Debagarh",
        "5": "Sundargarh",
        "6": "Kendujhar",
        "7": "Mayurbhanj",
        "8": "Baleshwar",
        "9": "Bhadrak",
        "10": "Kendrapara",
        "11": "Jagatsinghapur",
        "12": "Cuttack",
        "13": "Jajapur",
        "14": "Dhenkanal",
        "15": "Anugul",
        "16": "Nayagarh",
        "17": "Khordha",
        "18": "Puri",
        "19": "Ganjam",
        "20": "Gajapati",
        "21": "Kandhamal",
        "22": "Baudh",
        "23": "Subarnapur",
        "24": "Balangir",
        "25": "Nuapada",
        "26": "Kalahandi",
        "27": "Rayagada",
        "28": "Nabarangapur",
        "29": "Koraput",
        "30": "Malkangiri"
    },
    "22": {  # Chhattisgarh
        "1": "Koriya",
        "2": "Surguja",
        "3": "Jashpur",
        "4": "Raigarh",
        "5": "Korba",
        "6": "Janjgir-Champa",
        "7": "Bilaspur",
        "8": "Kabeerdham",
        "9": "Rajnandgaon",
        "10": "Durg",
        "11": "Raipur",
        "12": "Mahasamund",
        "13": "Dhamtari",
        "14": "Uttar Bastar Kanker",
        "15": "Bastar",
        "16": "Narayanpur",
        "17": "Dakshin Bastar Dantewada",
        "18": "Bijapur",
        "19": "Balodabazar",
        "20": "Gariyaband",
        "21": "Kondagaon",
        "22": "Sukama",
        "23": "Bemetara",
        "24": "Balod",
        "25": "Mungeli",
        "26": "Surajpur",
        "27": "Balrampur"
    },
    "23": {  # Madhya Pradesh
        "1": "Sheopur",
        "2": "Morena",
        "3": "Bhind",
        "4": "Gwalior",
        "5": "Datia",
        "6": "Shivpuri",
        "7": "Tikamgarh",
        "8": "Chhatarpur",
        "9": "Panna",
        "10": "Sagar",
        "11": "Damoh",
        "12": "Satna",
        "13": "Rewa",
        "14": "Umaria",
        "15": "Neemuch",
        "16": "Mandsaur",
        "17": "Ratlam",
        "18": "Ujjain",
        "19": "Shajapur",
        "20": "Dewas",
        "21": "Dhar",
        "22": "Indore",
        "23": "Khargone (West Nimar)",
        "24": "Barwani",
        "25": "Rajgarh",
        "26": "Vidisha",
        "27": "Bhopal",
        "28": "Sehore",
        "29": "Raisen",
        "30": "Betul",
        "31": "Harda",
        "32": "Hoshangabad",
        "33": "Katni",
        "34": "Jabalpur",
        "35": "Narsimhapur",
        "36": "Dindori",
        "37": "Mandla",
        "38": "Chhindwara",
        "39": "Seoni",
        "40": "Balaghat",
        "41": "Guna",
        "42": "Ashoknagar",
        "43": "Shahdol",
        "44": "Anuppur",
        "45": "Sidhi",
        "46": "Singrauli",
        "47": "Jhabua",
        "48": "Alirajpur",
        "49": "Khandwa (East Nimar)",
        "50": "Burhanpur"
    },
    "24": {  # Gujarat
        "1": "Kachchh",
        "2": "Banas Kantha",
        "3": "Patan",
        "4": "Mahesana",
        "5": "Sabar Kantha",
        "6": "Gandhinagar",
        "7": "Ahmedabad",
        "8": "Surendranagar",
        "9": "Rajkot",
        "10": "Jamnagar",
        "11": "Porbandar",
        "12": "Junagadh",
        "13": "Amreli",
        "14": "Bhavnagar",
        "15": "Anand",
        "16": "Kheda",
        "17": "Panch Mahals",
        "18": "Dohad",
        "19": "Vadodara",
        "20": "Narmada",
        "21": "Bharuch",
        "22": "The Dangs",
        "23": "Navsari",
        "24": "Valsad",
        "25": "Surat",
        "26": "Tapi",
        "27": "Arvalli",
        "28": "Botad",
        "29": "Chhota Udepur",
        "30": "DevBhumi-Dwarka",
        "31": "Gir Somnath",
        "32": "Mahisagar",
        "33": "Morbi"
    },
    "25": {  # Daman & Diu
        "1": "Diu",
        "2": "Daman"
    },
    "26": {  # Dadra & Nagar Haveli
        "1": "Dadra & Nagar Haveli"
    },
    "27": {  # Maharashtra
        "1": "Nandurbar",
        "2": "Dhule",
        "3": "Jalgaon",
        "4": "Buldana",
        "5": "Akola",
        "6": "Washim",
        "7": "Amravati",
        "8": "Wardha",
        "9": "Nagpur",
        "10": "Bhandara",
        "11": "Gondiya",
        "12": "Gadchiroli",
        "13": "Chandrapur",
        "14": "Yavatmal",
        "15": "Nanded",
        "16": "Hingoli",
        "17": "Parbhani",
        "18": "Jalna",
        "19": "Aurangabad",
        "20": "Nashik",
        "21": "Thane",
        "22": "Mumbai Suburban",
        "23": "Mumbai",
        "24": "Raigarh",
        "25": "Pune",
        "26": "Ahmadnagar",
        "27": "Bid",
        "28": "Latur",
        "29": "Osmanabad",
        "30": "Solapur",
        "31": "Satara",
        "32": "Ratnagiri",
        "33": "Sindhudurg",
        "34": "Kolhapur",
        "35": "Sangli"
    },
    "28": {  # Andhra Pradesh
        "1": "Srikakulam",
        "2": "Vizianagaram",
        "3": "Visakhapatnam",
        "4": "East Godavari",
        "5": "West Godavari",
        "6": "Krishna",
        "7": "Guntur",
        "8": "Prakasam",
        "9": "Sri Potti Sriramulu Nellore",
        "10": "Y.S.R. (Cuddapah)",
        "11": "Kurnool",
        "12": "Anantapur",
        "13": "Chittoor"
    },
    "29": {  # Karnataka
        "1": "Belgaum",
        "2": "Bagalkot",
        "3": "Bijapur",
        "4": "Bidar",
        "5": "Raichur",
        "6": "Koppal",
        "7": "Gadag",
        "8": "Dharwad",
        "9": "Uttara Kannada",
        "10": "Haveri",
        "11": "Bellary",
        "12": "Chitradurga",
        "13": "Davanagere",
        "14": "Shimoga",
        "15": "Udupi",
        "16": "Chikmagalur",
        "17": "Tumkur",
        "18": "Bangalore",
        "19": "Mandya",
        "20": "Hassan",
        "21": "Dakshina Kannada",
        "22": "Kodagu",
        "23": "Mysore",
        "24": "Chamarajanagar",
        "25": "Gulbarga",
        "26": "Yadgir",
        "27": "Kolar",
        "28": "Chikkaballapura",
        "29": "Bangalore (Rural)",
        "30": "Ramanagara"
    },
    "30": {  # Goa
        "1": "North Goa",
        "2": "South Goa"
    },
    "31": {  # Lakshadweep
        "1": "Lakshadweep"
    },
    "32": {  # Kerala
        "1": "Kasaragod",
        "2": "Kannur",
        "3": "Wayanad",
        "4": "Kozhikode",
        "5": "Malappuram",
        "6": "Palakkad",
        "7": "Thrissur",
        "8": "Ernakulam",
        "9": "Idukki",
        "10": "Kottayam",
        "11": "Alappuzha",
        "12": "Pathanamthitta",
        "13": "Kollam",
        "14": "Thiruvananthapuram"
    },
    "33": {  # Tamil Nadu
        "1": "Thiruvallur",
        "2": "Chennai",
        "3": "Kancheepuram",
        "4": "Vellore",
        "5": "Tiruvannamalai",
        "6": "Viluppuram",
        "7": "Salem",
        "8": "Namakkal",
        "9": "Erode",
        "10": "The Nilgiris",
        "11": "Dindigul",
        "12": "Karur",
        "13": "Tiruchirappalli",
        "14": "Perambalur",
        "15": "Ariyalur",
        "16": "Cuddalore",
        "17": "Nagapattinam",
        "18": "Thiruvarur",
        "19": "Thanjavur",
        "20": "Pudukkottai",
        "21": "Sivaganga",
        "22": "Madurai",
        "23": "Theni",
        "24": "Virudhunagar",
        "25": "Ramanathapuram",
        "26": "Thoothukkudi",
        "27": "Tirunelveli",
        "28": "Kanniyakumari",
        "29": "Dharmapuri",
        "30": "Krishnagiri",
        "31": "Coimbatore",
        "32": "Tiruppur"
    },
    "34": {  # Puducherry
        "1": "Yanam",
        "2": "Puducherry",
        "3": "Mahe",
        "4": "Karaikal"
    },
    "35": {  # Andaman & Nicobar Islands
        "1": "Nicobars",
        "2": "North & Middle Andaman",
        "3": "South Andaman"
    },
    "36": {  # Telangana
        "1": "Adilabad",
        "2": "Komaram Bheem",
        "3": "Mancherial",
        "4": "Nirmal",
        "5": "Nizamabad",
        "6": "Jagtial",
        "7": "Peddapalli",
        "8": "Jayashankar",
        "9": "Bhadradri",
        "10": "Mahabubabad",
        "11": "Warangal Rural",
        "12": "Warangal Urban",
        "13": "Karimnagar",
        "14": "Rajanna",
        "15": "Kamareddy",
        "16": "Sangareddy",
        "17": "Medak",
        "18": "Siddipet",
        "19": "Jangaon",
        "20": "Yadadri",
        "21": "Medchal-Malkajgiri",
        "22": "Hyderabad",
        "23": "Rangareddy",
        "24": "Vikarabad",
        "25": "Mahbubnagar",
        "26": "Jogulamba",
        "27": "Wanaparthy",
        "28": "Nagarkurnool",
        "29": "Nalgonda",
        "30": "Suryapet",
        "31": "Khammam"
    }
}

# Marital status mapping
MARITAL_STATUS_MAPPING = {
    "1": "never married",
    "2": "currently married",
    "3": "widowed",
    "4": "divorced/separated"
}

# Gender mapping
GENDER_MAPPING = {
    "1": "male",
    "2": "female",
    "3": "transgender"
}

# Enterprise type mapping
ENTERPRISE_TYPE_MAPPING = {
    "1": "proprietary",
    "2": "partnership",
    "3": "government/local body",
    "4": "autonomous bodies",
    "5": "public/private limited company",
    "6": "cooperative societies",
    "7": "trust/other non-profit institutions",
    "8": "employer's households",
    "9": "others"
}

# Activity location mapping
ACTIVITY_LOCATION_MAPPING = {
    "1": "home",
    "2": "fixed location",
    "3": "non-fixed location"
}

# Activity code mapping
ACTIVITY_CODE_MAPPING = {
    "110": "Employment in corporations, government and non-profit institutions",
    "121": "Growing of crops for the market in household enterprises",
    "122": "Raising animals for the market in household enterprises",
    "123": "Forestry and logging for the market in household enterprises",
    "124": "Fishing for the market in household enterprises",
    "125": "Aquaculture for the market in household enterprises",
    "126": "Mining and quarrying for the market in household enterprises",
    "127": "Making and processing goods for the market in household enterprises",
    "128": "Construction activities for the market in household enterprises",
    "129": "Other activities related to employment in household enterprises to produce goods",
    "131": "Vending and trading of goods in household enterprises",
    "132": "Providing paid repair, installation, maintenance and disposal in household enterprises",
    "133": "Providing paid business and professional services in household enterprises",
    "134": "Transporting goods and passengers for pay or profit in household enterprises",
    "135": "Providing paid personal care services in household enterprises",
    "136": "Providing paid domestic services",
    "139": "Other activities related to employment in household enterprises providing services",
    "141": "Activities ancillary to employment",
    "142": "Breaks during working time within employment",
    "150": "Training and studies in relation to employment",
    "160": "Seeking employment",
    "170": "Setting up a business",
    "181": "Employment-related travel",
    "182": "Commuting",
    "211": "Growing crops and kitchen gardening, for own final use",
    "212": "Farming of animals and production of animal products for own final use",
    "213": "Hunting, trapping and production of animal skins for own final use",
    "214": "Forestry and logging for own final use",
    "215": "Gathering wild products for own final use",
    "216": "Fishing for own final use",
    "217": "Aquaculture for own final use",
    "218": "Mining and quarrying for own final use",
    "221": "Making, processing food products, beverages and tobacco for own final use",
    "222": "Making, processing textiles, wearing apparel, leather and related products for own final use",
    "223": "Making, processing of wood and bark products for own final use",
    "224": "Making, processing bricks, concrete slabs, hollow blocks, tiles for own final use",
    "225": "Making, processing herbal and medicinal preparations for own final use",
    "226": "Making, processing metals and metal products for own final use",
    "227": "Making, processing of products using other materials for own final use",
    "229": "Acquiring supplies and disposing of products and other activities related to making and processing goods for own final use",
    "230": "Construction activities for own final use",
    "241": "Gathering firewood and other natural products used as fuel for own final use",
    "242": "Fetching water from natural and other sources for own final use",
    "250": "Travelling, moving, transporting or accompanying goods or persons related to own-use production of goods",
    "311": "Preparing meals/snacks",
    "312": "Serving meals/snacks",
    "313": "Cleaning up after food preparation/meals/snacks",
    "314": "Storing, arranging, preserving food stocks",
    "319": "Other activities related to food and meals management and preparation",
    "321": "Indoor cleaning",
    "322": "Outdoor cleaning",
    "323": "Recycling and disposal of garbage",
    "324": "Upkeep of indoor/outdoor plants, hedges, garden, grounds, landscape, etc.",
    "325": "Tending furnace, boiler, fireplace for heating and water supply",
    "329": "Other activities related to cleaning and upkeep of dwelling and surroundings",
    "331": "Do-it-yourself improvement, maintenance and repair of own dwelling",
    "332": "Installation, servicing and repair of personal and household goods including ICT equipment",
    "333": "Vehicle maintenance and repairs",
    "339": "Other activities related to do-it-yourself decoration, maintenance and repair",
    "341": "Hand/machine-washing",
    "342": "Drying textiles and clothing",
    "343": "Ironing/pressing/folding",
    "344": "Mending/repairing and care of clothes and shoes; cleaning and polishing shoes",
    "349": "Other activities related to care of textiles and footwear",
    "351": "Paying household bills",
    "352": "Budgeting, planning, organizing duties and activities in the household",
    "359": "Other activities related to household management",
    "361": "Daily pet care",
    "362": "Using veterinary care or other pet care services (grooming, stabling, holiday or day care)",
    "369": "Other activities related to pet care",
    "371": "Shopping for/purchasing of goods and related activities",
    "372": "Shopping for/availing of services and related activity",
    "380": "Travelling, moving, transporting or accompanying goods or persons related to unpaid domestic services for household members",
    "390": "Other unpaid domestic services for household members",
    "411": "Caring for children including feeding, cleaning, physical care",
    "412": "Providing medical care to children",
    "413": "Instructing, teaching, training, helping children",
    "414": "Talking with and reading to children",
    "415": "Playing and sports with children",
    "416": "Minding children (passive care)",
    "417": "Meetings and arrangements with schools and child care service providers",
    "419": "Other activities related to childcare and instruction",
    "421": "Assisting dependent adults with tasks of daily living",
    "422": "Assisting dependent adults with medical care",
    "423": "Assisting dependent adults with forms, administration, accounts",
    "424": "Affective/emotional support for dependent adults",
    "425": "Passive care of dependent adult",
    "426": "Meetings and arrangements with adult care service providers",
    "429": "Other activities related to care for dependent adults",
    "43": "Help to non-dependent adult household members",
    "431": "Feeding, cleaning, physical care for non-dependent adult household members including for temporary illness",
    "432": "Affective/emotional support for non-dependent adult household members",
    "439": "Other activities related to care for non-dependent adult household members",
    "441": "Travelling related to care-giving services for household members",
    "442": "Accompanying own children",
    "443": "Accompanying dependent adults",
    "444": "Accompanying non-dependent adult household members",
    "490": "Other activities related to unpaid caregiving services for household members ",
    "511": "Unpaid volunteer household maintenance, management, construction, renovation and repair",
    "512": "Unpaid volunteer shopping/purchasing goods and services",
    "513": "Unpaid volunteer childcare and instruction",
    "514": "Unpaid volunteer care for adults",
    "515": "Unpaid volunteer activities in enterprises owned by other households",
    "519": "Other activities related to direct unpaid volunteering for other households",
    "521": "Unpaid volunteer work on road/building repair, clearing and preparing land, cleaning (streets, markets, etc.), and construction",
    "522": "Unpaid volunteer preparing/serving meals, cleaning up",
    "523": "Unpaid volunteer cultural activities, recreation and sports activities",
    "524": "Unpaid volunteer office/administrative work",
    "529": "Other activities related to community- and organizationbased unpaid volunteering",
    "530": "Unpaid trainee work and related activities",
    "540": "Travelling time related to unpaid volunteer, trainee and other unpaid work",
    "590": "Other unpaid work activities",
    "611": "School/university attendance",
    "612": "Extra-curricular activities",
    "613": "Breaks at place of formal education",
    "614": "Self-study for distance education course work (video, audio, online)",
    "619": "Other activities related to formal education",
    "62": "Homework, being tutored, course review, research and activities related to formal education",
    "620": "Homework, being tutored, course review, research and activities related to formal education",
    "630": "Additional study, non-formal education and courses",
    "640": "Travelling time related to learning",
    "690": "Other activities related to learning",
    "711": "Talking, conversing, chatting",
    "712": "Socializing/getting together/gathering activities",
    "713": "Reading and writing mail (including email)",
    "719": "Other activities related to socializing and communication",
    "721": "Participating in community celebrations of cultural/historic events",
    "722": "Participating in community rites/events (non-religious) of weddings, funerals, births and similar rites-ofpassage",
    "723": "Participating in community social functions (music, dance, etc.)",
    "729": "Other activities related to community participation",
    "730": "Involvement in civic and related responsibilities",
    "741": "Private prayer, meditation and other spiritual activities",
    "742": "Participating in collective religious practice",
    "749": "Other activities related to religious practice",
    "750": "Travelling time related to socializing and communication, community participation and religious practice",
    "790": "Culture, leisure, mass-media and sports practices",
    "81": "Attending/visiting cultural, entertainment and sports events/venues",
    "811": "Attendance at organized/mass cultural events and shows",
    "812": "Attendance at parks/gardens",
    "813": "Attendance at sports events",
    "819": "Other activities related to attendance at cultural, entertainment and sports events",
    "821": "Visual, literary and performing arts (as hobby)",
    "822": "Hobbies",
    "823": "Playing games and other pastime activities",
    "829": "Other activities related to cultural participation, hobbies, games",
    "831": "Participating in sports",
    "832": "Exercising",
    "841": "Reading for leisure",
    "842": "Watching/listening to television and video",
    "843": "Listening to radio and audio devices",
    "849": "Other activities related to mass media use",
    "850": "Activities associated with reflecting, resting, relaxing",
    "860": "Travelling time related to culture, leisure, mass-media and sports practices",
    "890": "Other activities related to culture, leisure, mass-media and sports practices",
    "911": "Night sleep/essential sleep",
    "912": "Incidental sleep/naps",
    "913": "Sleeplessness",
    "919": "Other sleep and related activities",
    "921": "Eating meals/snack",
    "922": "Drinking other than with meal or snack",
    "931": "Personal hygiene and care",
    "932": "Health/medical care to oneself",
    "939": "Other activities related to personal hygiene and care",
    "941": "Receiving personal care from others",
    "942": "Receiving health/medical care from others",
    "949": "Other activities related to receiving personal and health/medical care",
    "950": "Travelling time related to self-care and maintenance activities",
    "990": "Other self-care and maintenance activities",
}

# Principal activity status mapping
PRINCIPAL_ACTIVITY_MAPPING = {
    "11": "worked in household enterprises (self-employed) as own-account worker",
    "12": "worked in household enterprises (self-employed) as an employer",
    "21": "worked in household enterprises (self-employed) as helper",
    "31": "worked as regular wage/salaried employee",
    "41": "worked as casual labour in public works",
    "51": "worked as casual labour in other types of works",
    "81": "sought work or did not seek but was available for work",
    "91": "attended educational institutions",
    "92": "attended to domestic duties only",
    "93": "attended to domestic duties and was also engaged in free collection of goods for household use",
    "94": "rentiers, pensioners, remittance recipients, etc.",
    "95": "not able to work owing to disability",
    "97": "others (including beggars, prostitutes, etc.)",
    "99": "children of age 0-4 years"
}

# Payment status mapping
PAYMENT_STATUS_MAPPING = {
    "1": "self development/self care/self maintenance",
    "2": "care for children, sick, elderly, differently-abled persons in own households",
    "3": "production of other services (except care activities) for own consumption",
    "4": "production of goods for own consumption",
    "5": "voluntary work for production of goods in households",
    "6": "voluntary work for production of services in households",
    "7": "voluntary work for production of goods in market/non-market units",
    "8": "voluntary work for production of services in market/non-market units",
    "9": "unpaid trainee work for production of goods",
    "10": "unpaid trainee work for production of services",
    "11": "other unpaid work for production of goods",
    "12": "other unpaid work for production of services",
    "13": "self-employment: for production of goods",
    "14": "self-employment: for production of services",
    "15": "regular wage/salary: for production of goods",
    "16": "regular wage/salary: for production of services",
    "17": "casual labour: for production of goods",
    "18": "casual labour: for production of services"
}

# Industry code mapping
INDUSTRY_CODE_MAPPING = {
    "1": "Crop and animal production, hunting and related service activities",
    "2": "Forestry and logging",
    "3": "Fishing and aquaculture",
    "5": "Mining of coal and lignite",
    "6": "Extraction of crude petroleum and natural gas",
    "7": "Mining of metal ores",
    "8": "Other mining and quarrying",
    "9": "Mining support service activities",
    "10": "Manufacture of food products",
    "11": "Manufacture of beverages",
    "12": "Manufacture of tobacco products",
    "13": "Manufacture of textiles",
    "14": "Manufacture of wearing apparel",
    "15": "Manufacture of leather and related products",
    "16": "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",
    "17": "Manufacture of paper and paper products",
    "18": "Printing and reproduction of recorded media",
    "19": "Manufacture of coke and refined petroleum products",
    "20": "Manufacture of chemicals and chemical products",
    "21": "Manufacture of pharmaceuticals, medicinal chemical and botanical products",
    "22": "Manufacture of rubber and plastics products",
    "23": "Manufacture of other non-metallic mineral products",
    "24": "Manufacture of basic metals",
    "25": "Manufacture of fabricated metal products, except machinery and equipment",
    "26": "Manufacture of computer, electronic and optical products",
    "27": "Manufacture of electrical equipment",
    "28": "Manufacture of machinery and equipment n.e.c.",
    "29": "Manufacture of motor vehicles, trailers and semi-trailers",
    "30": "Manufacture of other transport equipment",
    "31": "Manufacture of furniture",
    "32": "Other manufacturing",
    "33": "Repair and installation of machinery and equipment",
    "35": "Electricity, gas, steam and air conditioning supply",
    "36": "Water collection, treatment and supply",
    "37": "Sewerage",
    "38": "Waste collection, treatment and disposal activities; materials recovery",
    "39": "Remediation activities and other waste management services",
    "41": "Construction of buildings",
    "42": "Civil engineering",
    "43": "Specialized construction activities",
    "45": "Wholesale and retail trade and repair of motor vehicles and motorcycles",
    "46": "Wholesale trade, except of motor vehicles and motorcycles",
    "47": "Retail trade, except of motor vehicles and motorcycles",
    "49": "Land transport and transport via pipelines",
    "50": "Water transport",
    "51": "Air transport",
    "52": "Warehousing and support activities for transportation",
    "53": "Postal and courier activities",
    "55": "Accommodation",
    "56": "Food and beverage service activities",
    "58": "Publishing activities",
    "59": "Motion picture, video and television programme production, sound recording and music publishing activities",
    "60": "Broadcasting and programming activities",
    "61": "Telecommunications",
    "62": "Computer programming, consultancy and related activities",
    "63": "Information service activities",
    "64": "Financial service activities, except insurance and pension funding",
    "65": "Insurance, reinsurance and pension funding, except compulsory social security",
    "66": "Other financial activities",
    "68": "Real estate activities",
    "69": "Legal and accounting activities",
    "70": "Activities of head offices; management consultancy activities",
    "71": "Architecture and engineering activities; technical testing and analysis",
    "72": "Scientific research and development",
    "73": "Advertising and market research",
    "74": "Other professional, scientific and technical activities",
    "75": "Veterinary activities",
    "77": "Rental and leasing activities",
    "78": "Employment activities",
    "79": "Travel agency, tour operator and other reservation service activities",
    "80": "Security and investigation activities",
    "81": "Services to buildings and landscape activities",
    "82": "Office administrative, office support and other business support activities",
    "84": "Public administration and defence; compulsory social security",
    "85": "Education",
    "86": "Human health activities",
    "87": "Residential care activities",
    "88": "Social work activities without accommodation",
    "90": "Creative, arts and entertainment activities",
    "91": "Libraries, archives, museums and other cultural activities",
    "92": "Gambling and betting activities",
    "93": "Sports activities and amusement and recreation activities",
    "94": "Activities of membership organizations",
}